### ISSUE TITLE
Falta propiedad color en el componente k-icon

### ISSUE THREAD

**Issue by FelipeGCx** [calltek/kodama#5]
# Descripción:
al momento de usar la etiqueta se observa que el componente [`k-icon`](https://github.com/calltek/kodama/blob/main/src/components/general/k-icon/k-icon.vue) no tiene el `prop` `color` para poder darle un color especifio al icono que se muestra, por esta razón es necesario implementarlo

**Comment by 50l3r** [comment]
Añadida propiedad `color` para el componente `k-input`

Version: `0.21`
