### ISSUE TITLE
Falta manejo de requerido en el k-checkbox

### ISSUE THREAD

**Issue by FelipeGCx** [calltek/kodama#6]
# Descripción:
el componente [`k-checkbox`](https://github.com/calltek/kodama/blob/main/src/components/data-entry/k-checkbox/k-checkbox.vue) no dispone de un manejo en el caso de ser requerido, se esperaría que se contemple con el fin de poner usarlo.

**Comment by 50l3r** [comment]
Añadido campo `required` en la version `0.21`
